name: Bug Report
about: Create a report to help us improve

on:
  push:
    branches:
      - main

jobs:
  bug-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Issue
        run: |
          echo "---
          name: Bug Report
          about: Create a report to help us improve
          title: ''
          labels: bug
          assignees: ''
          ---

          **Describe the bug**

          A clear and concise description of what the bug is.

          **To Reproduce**

          Steps to reproduce the behavior:

          1. Go to '...'
          2. Click on '....'
          3. Scroll down to '....'
          4. See error

          **Expected behavior**

          A clear and concise description of what you expected to happen.

          **Screenshots**

          If applicable, add screenshots to help explain your problem.

          **Desktop (please complete the following information):**

          - OS: [e.g. Windows, macOS]
          - Browser: [e.g. Chrome, Firefox]
          - Version: [e.g. 22]

          **Smartphone (please complete the following information):**

          - Device: [e.g. iPhone6]
          - OS: [e.g. iOS8.1]
          - Browser: [e.g. stock browser, Safari]
          - Version: [e.g. 22]

          **Additional context**

          Add any other context about the problem here." > issue.md

          echo "Issue created at ${{ github.event.repository.html_url }}/issues/new" > url.txt
        shell: bash
        env:
          ISSUE: ${{ steps.bug-report.outputs.issue }}
        continue-on-error: true

      - name: Create Issue Comment
        if: failure()
        run: |
          issue=$(cat issue.md)
          comment="Something went wrong when creating the issue. Please [click here]($(cat url.txt)) to create the issue manually."
          echo $comment > comment.md
          curl -d "$comment" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
        shell: bash
